name             'tc'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures tc'
long_description 'Installs/Configures tc'
version          '0.1.0'
